from reportlab.lib.colors import HexColor, black
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm

try:
    from backend.reporting.hash_utils import PDF_CREATOR, PDF_PRODUCER, PLATFORM_NAME, PLATFORM_VERSION
except ModuleNotFoundError:
    from reporting.hash_utils import PDF_CREATOR, PDF_PRODUCER, PLATFORM_NAME, PLATFORM_VERSION


MICRO_WATERMARK_TEXT = "ALFA HAWK • ALFA HAWK • ALFA HAWK "
FOOTER_ATTRIBUTION = "Generated by Alfa Hawk — AI Evidence Analysis Platform"
MICRO_WATERMARK_COLOR = HexColor('#808080')
FOOTER_COLOR = HexColor('#64748b')
RESTRICTED_COLOR = HexColor('#dc2626')


def apply_page_watermarks(canvas_obj, doc, include_footer=True):
    canvas_obj.saveState()
    _draw_micro_border_watermark(canvas_obj)
    _inject_pdf_metadata(canvas_obj, doc)
    if include_footer:
        _draw_footer_attribution(canvas_obj)
    canvas_obj.setFont('Helvetica-Bold', 7)
    canvas_obj.setFillColor(RESTRICTED_COLOR)
    canvas_obj.drawRightString(A4[0] - 15 * mm, A4[1] - 10 * mm, 'RESTRICTED')
    canvas_obj.restoreState()


def _draw_micro_border_watermark(canvas_obj):
    canvas_obj.setFont('Helvetica-Bold', 2)
    canvas_obj.setFillColor(MICRO_WATERMARK_COLOR)
    canvas_obj.setFillAlpha(0.15)
    watermark_width = canvas_obj.stringWidth(MICRO_WATERMARK_TEXT, 'Helvetica-Bold', 2)

    x = 10 * mm
    while x < A4[0] - 10 * mm:
        canvas_obj.drawString(x, A4[1] - 12 * mm, MICRO_WATERMARK_TEXT)
        x += watermark_width

    x = 10 * mm
    while x < A4[0] - 10 * mm:
        canvas_obj.drawString(x, 12 * mm, MICRO_WATERMARK_TEXT)
        x += watermark_width

    canvas_obj.saveState()
    canvas_obj.rotate(90)
    y = 10 * mm
    while y < A4[1] - 10 * mm:
        canvas_obj.drawString(y, -12 * mm, MICRO_WATERMARK_TEXT)
        y += watermark_width
    canvas_obj.restoreState()

    canvas_obj.saveState()
    canvas_obj.rotate(-90)
    y = -(A4[1] - 10 * mm)
    while y < -10 * mm:
        canvas_obj.drawString(y, A4[0] - 12 * mm, MICRO_WATERMARK_TEXT)
        y += watermark_width
    canvas_obj.restoreState()

    canvas_obj.setFillAlpha(1.0)
    canvas_obj.setFillColor(black)


def _draw_footer_attribution(canvas_obj):
    canvas_obj.setFont('Helvetica', 7)
    canvas_obj.setFillColor(FOOTER_COLOR)
    canvas_obj.drawCentredString(
        A4[0] / 2,
        8 * mm,
        FOOTER_ATTRIBUTION
    )


def _inject_pdf_metadata(canvas_obj, doc):
    canvas_obj.setAuthor(getattr(doc, 'pdf_creator', PDF_CREATOR))
    canvas_obj.setCreator(getattr(doc, 'pdf_creator', PDF_CREATOR))
    canvas_obj.setTitle(f'Forensic Report {getattr(doc, "report_id", "N/A")}')
    canvas_obj.setSubject(f'Forensic Analysis - {getattr(doc, "report_id", "N/A")}')
    canvas_obj.setKeywords(
        'Producer=' + getattr(doc, 'pdf_producer', PDF_PRODUCER) +
        ', Creator=' + getattr(doc, 'pdf_creator', PDF_CREATOR) +
        ', Platform=' + getattr(doc, 'platform_name', PLATFORM_NAME) +
        ', Platform-Version=' + getattr(doc, 'platform_version', PLATFORM_VERSION) +
        ', Report-ID=' + getattr(doc, 'report_id', 'N/A') +
        ', Generated-Timestamp=' + getattr(doc, 'generated_at_iso', 'N/A') +
        ', Report-Integrity-Hash=' + getattr(doc, 'report_hash', 'N/A')
    )
    info = canvas_obj._doc.info
    info.producer = getattr(doc, 'pdf_producer', PDF_PRODUCER)
