from reportlab.lib.colors import HexColor, black
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm

try:
    from backend.reporting.hash_utils import PDF_CREATOR, PDF_PRODUCER, PLATFORM_NAME, PLATFORM_VERSION
except ModuleNotFoundError:
    from reporting.hash_utils import PDF_CREATOR, PDF_PRODUCER, PLATFORM_NAME, PLATFORM_VERSION


# ─────────────────────────────────────────────────────────
# WATERMARK CONFIGURATION
# ─────────────────────────────────────────────────────────
# Single unit — looks like a frame, not a wall of text
_WM_UNIT = "ALFA HAWK"
_WM_SEPARATOR = " \u2022 "
# Build the repeating text: only 3 repetitions per segment
MICRO_WATERMARK_TEXT = (_WM_UNIT + _WM_SEPARATOR) * 3

FOOTER_ATTRIBUTION = "Generated by Alfa Hawk \u2014 AI Evidence Analysis Platform"
MICRO_WATERMARK_COLOR = HexColor('#9ca3af')   # lighter grey for subtlety
FOOTER_COLOR = HexColor('#64748b')
RESTRICTED_COLOR = HexColor('#dc2626')

# Border layout — generous insets to keep watermark outside content
_BORDER_INSET = 5 * mm       # distance from page edge
_CORNER_GAP = 10 * mm        # blank space at corners for clean alignment
_WM_FONT_SIZE = 3            # small but legible micro-text
_WM_GAP = 4 * mm             # explicit spacing between repeated segments
_WM_OPACITY = 0.10           # very subtle


def apply_page_watermarks(canvas_obj, doc, include_footer=True):
    canvas_obj.saveState()
    _draw_micro_border_watermark(canvas_obj)
    _inject_pdf_metadata(canvas_obj, doc)
    if include_footer:
        _draw_footer_attribution(canvas_obj, doc)
    # RESTRICTED badge — top-right, inside content area, clear of watermark
    canvas_obj.setFont('Helvetica-Bold', 7)
    canvas_obj.setFillColor(RESTRICTED_COLOR)
    canvas_obj.drawRightString(A4[0] - 22 * mm, A4[1] - 18 * mm, 'RESTRICTED')
    canvas_obj.restoreState()


def _draw_micro_border_watermark(canvas_obj):
    """Draw a clean branded border frame on all four edges.

    Design goals:
    - Reduced density: segments separated by explicit gap
    - Equal repetition count on top and bottom
    - Vertical orientation on left and right borders
    - Corner gaps so borders don't collide
    - Clear margin between watermark and content
    """
    page_w, page_h = A4
    canvas_obj.setFont('Helvetica-Bold', _WM_FONT_SIZE)
    canvas_obj.setFillColor(MICRO_WATERMARK_COLOR)
    canvas_obj.setFillAlpha(_WM_OPACITY)
    seg_width = canvas_obj.stringWidth(MICRO_WATERMARK_TEXT, 'Helvetica-Bold', _WM_FONT_SIZE)
    stride = seg_width + _WM_GAP  # gap between repeated segments

    # Calculate how many segments fit on each edge
    horiz_available = page_w - 2 * (_BORDER_INSET + _CORNER_GAP)
    vert_available = page_h - 2 * (_BORDER_INSET + _CORNER_GAP)
    horiz_count = max(1, int(horiz_available / stride))
    vert_count = max(1, int(vert_available / stride))

    # Center the segments on each edge for symmetry
    horiz_total = horiz_count * stride - _WM_GAP
    horiz_start = _BORDER_INSET + _CORNER_GAP + (horiz_available - horiz_total) / 2
    vert_total = vert_count * stride - _WM_GAP
    vert_start = _BORDER_INSET + _CORNER_GAP + (vert_available - vert_total) / 2

    # ── TOP border (horizontal) ──
    x = horiz_start
    for _ in range(horiz_count):
        canvas_obj.drawString(x, page_h - _BORDER_INSET, MICRO_WATERMARK_TEXT)
        x += stride

    # ── BOTTOM border (horizontal, same count as top) ──
    x = horiz_start
    for _ in range(horiz_count):
        canvas_obj.drawString(x, _BORDER_INSET, MICRO_WATERMARK_TEXT)
        x += stride

    # ── LEFT border (vertical, bottom to top) ──
    canvas_obj.saveState()
    canvas_obj.rotate(90)
    y = vert_start
    for _ in range(vert_count):
        canvas_obj.drawString(y, -_BORDER_INSET, MICRO_WATERMARK_TEXT)
        y += stride
    canvas_obj.restoreState()

    # ── RIGHT border (vertical, top to bottom) ──
    canvas_obj.saveState()
    canvas_obj.rotate(-90)
    y = -(page_h - vert_start)
    for _ in range(vert_count):
        canvas_obj.drawString(y, page_w - _BORDER_INSET, MICRO_WATERMARK_TEXT)
        y += stride
    canvas_obj.restoreState()

    # Reset alpha
    canvas_obj.setFillAlpha(1.0)
    canvas_obj.setFillColor(black)


def _draw_footer_attribution(canvas_obj, doc=None):
    page_w = A4[0]
    page_num = canvas_obj.getPageNumber()
    # Page number — right side
    canvas_obj.setFont('Helvetica', 6)
    canvas_obj.setFillColor(FOOTER_COLOR)
    canvas_obj.drawRightString(page_w - 22 * mm, 18 * mm, f'Page {page_num}')
    # Attribution — centered
    canvas_obj.setFont('Helvetica', 7)
    canvas_obj.drawCentredString(page_w / 2, 18 * mm, FOOTER_ATTRIBUTION)


def _inject_pdf_metadata(canvas_obj, doc):
    canvas_obj.setAuthor(getattr(doc, 'pdf_creator', PDF_CREATOR))
    canvas_obj.setCreator(getattr(doc, 'pdf_creator', PDF_CREATOR))
    canvas_obj.setTitle(f'Forensic Report {getattr(doc, "report_id", "N/A")}')
    canvas_obj.setSubject(f'Forensic Analysis - {getattr(doc, "report_id", "N/A")}')
    canvas_obj.setKeywords(
        'Producer=' + getattr(doc, 'pdf_producer', PDF_PRODUCER) +
        ', Creator=' + getattr(doc, 'pdf_creator', PDF_CREATOR) +
        ', Platform=' + getattr(doc, 'platform_name', PLATFORM_NAME) +
        ', Platform-Version=' + getattr(doc, 'platform_version', PLATFORM_VERSION) +
        ', Report-ID=' + getattr(doc, 'report_id', 'N/A') +
        ', Generated-Timestamp=' + getattr(doc, 'generated_at_iso', 'N/A') +
        ', Report-Integrity-Hash=' + getattr(doc, 'report_hash', 'N/A')
    )
    info = canvas_obj._doc.info
    info.producer = getattr(doc, 'pdf_producer', PDF_PRODUCER)
